# Generated by Django 3.0.5 on 2020-04-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(blank=True, max_length=120, null=True)),
                ('Address2', models.CharField(blank=True, max_length=120, null=True)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('TaxID', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('NAICS', models.IntegerField()),
                ('HasBeenProfitable', models.BooleanField(null=True)),
                ('HasBankruptedInLast7Years', models.BooleanField(null=True)),
                ('InceptionDate', models.DateTimeField()),
                ('Address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CFApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('StatedCreditHistory', models.IntegerField()),
                ('LegalEntityType', models.CharField(max_length=20)),
                ('FilterID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.IntegerField()),
                ('RequestDate', models.DateTimeField()),
                ('CFApiUserId', models.IntegerField(blank=True, null=True)),
                ('CFApiPassword', models.CharField(blank=True, max_length=20, null=True)),
                ('IsTestLead', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportedCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualRevenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MonthlyAverageBankBalance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MonthlyAverageCreditCardVolume', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Business')),
                ('CFApplicationData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.CFApplicationData')),
                ('RequestHeader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.RequestHeader')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('DateOfBirth', models.DateTimeField()),
                ('HomePhone', models.IntegerField()),
                ('SSN', models.IntegerField()),
                ('PercentageOfOwnership', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HomeAddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.Address')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owners', to='status.Status')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='SelfReportedCashFlow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.SelfReportedCashFlow'),
        ),
    ]
